### ISSUE TITLE
Can it handle IPv6 /64?

### ISSUE THREAD

**Issue by TehPeGaSuS** [TotallyNotRobots/bnc-bot#1]
Hello,

From what I can see on the README, the bot `Assigns each user a unique bindhost in the 127.0.0.0/16 range`.

My question is: can it handle a /64 block from an IPv6 subnet, so it generates/assigns a different IPv6 address for each user?

Thanks in advance.

**Comment by linuxdaemon** [comment]
Currently it doesn't support configuring the subnet but I can add support for configuring the bindhost subnet, yep.

**Comment by linuxdaemon** [comment]
After looking over the code, yes in its current state it will handle v4 and v6 ranges specified in the config file, I forgot I already had it reading from the config
